### Lista usuários
GET http://localhost:8080/api/users

### Lista campanhas
GET http://localhost:8080/api/campaigns

### Buscar campanhas pelo Titulo
GET http://localhost:8080/api/campaigns/byTitle?title=Quest

### Buscar campanhas pelo Sistema de Regras
GET http://localhost:8080/api/campaigns/bySystemRules?systemRule=D

### Cadastrar campanhas 1
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "First Quest",
  "systemRule": "DAEMON",
  "password": "secretpassword",
  "maxPlayers": 4

}

### Cadastrar campanha 2
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Second Quest",
  "systemRule": "DND",
  "password": "beholdbeholder",
  "maxPlayers": 6
}

### Teste Cadastro campanha invalida
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Any Quest",
  "systemRules": "ystem",
  "password": "AnyPassword123",
  "maxPlayers": 9
}

### Teste Cadastro campanha Sem autorização
POST http://localhost:8080/api/campaigns
Content-Type: application/json

{
  "title": "Unauthorized Quest",
  "systemRules": "Gurps",
  "password": "AllWorldSkills",
  "maxPlayers": 9
}

### Listar campanha id = #
GET http://localhost:8080/api/campaigns/1



### Deletar Campanha = #
DELETE http://localhost:8080/api/campaigns/1
Authorization: Bearer {{token}}

### Inserir usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=1&idUser=2&action=add
Authorization: Bearer {{token}}

### Remover usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=1&idUser=1&action=remove
Authorization: Bearer {{token}}
