### Lista campanhas
GET http://localhost:8080/api/campaigns

### Buscar campanhas pelo Titulo
GET http://localhost:8080/api/campaigns/byTitle?title=Second

### Buscar campanhas pelo Sistema de Regras
GET http://localhost:8080/api/campaigns/bySystemRules?systemRule=DAEM

### Cadastrar campanhas 1
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "First Quest",
  "systemRules": "DAEMON",
  "password": "secretpassword",
  "maxPlayers": 4

}

### Cadastrar campanha 2
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Second Quest",
  "systemRules": "D&D",
  "password": "beholdbeholder",
  "maxPlayers": 6
}

### Teste Cadastro campanha invalida
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Any Quest",
  "systemRules": "AnySystem",
  "password": "AnyPassword123",
  "maxPlayers": 9
}

### Teste Cadastro campanha Sem autorização
POST http://localhost:8080/api/campaigns
Content-Type: application/json

{
  "title": "Unauthorized Quest",
  "systemRules": "Gurps",
  "password": "AllWorldSkills",
  "maxPlayers": 9
}

### Listar campanha id = #
GET http://localhost:8080/api/campaigns/5



### Deletar Campanha = #
DELETE http://localhost:8080/api/campaigns/1
Authorization: Bearer {{token}}

### Inserir usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=1&idUser=3&action=add
Authorization: Bearer {{token}}

### Remover usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=1&idUser=1&action=remove
Authorization: Bearer {{token}}

### Login do Usuario 4
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "player4@google.com",
  "password": "pl@y3r4890"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)

%}

### Login do ADMIN
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "gamemaster@google.com",
  "password": "gam3m@st3r0"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)

%}

