### Lista usuários
GET http://localhost:8080/api/users

### Lista campanhas
GET http://localhost:8080/api/campaigns

### Cadastrar Usuario 4
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "player4@google.com",
  "password": "pl@y3r4890",
  "name": "Player Quatro"

}

### Login do ADMIN
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "gamemaster@google.com",
  "password": "gam3m@st3r0"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)

%}

### Lista o próprio usuário
GET http://localhost:8080/api/users/me
Authorization: Bearer {{token}}

### Cadastrar campanhas 1
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "First Quest",
  "systemRule": "DAEMON",
  "password": "secretpassword",
  "maxPlayers": 4

}

### Login do Usuario 4
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "player4@google.com",
  "password": "pl@y3r4890"
}
> {%
    client.global.set("token", response.body.token)
    client.global.set("id", response.body.user.id)

%}

### Cadastrar campanha 2
POST http://localhost:8080/api/campaigns
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Second Quest",
  "systemRule": "DND",
  "password": "beholdbeholder",
  "maxPlayers": 6
}

### Deletar Campanha = # Proibido por ser a campanha do admin
DELETE http://localhost:8080/api/campaigns/1
Authorization: Bearer {{token}}

### Inserir usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=3&idUser=1&action=add
Authorization: Bearer {{token}}

### Deletar Campanha = # Prodibido pois tem mais de 1 usuário na campanha
DELETE http://localhost:8080/api/campaigns/2
Authorization: Bearer {{token}}

### Remover usuário na campanha = #
PUT http://localhost:8080/api/campaigns/user?idCampaing=2&idUser=1&action=remove
Authorization: Bearer {{token}}
